development:
  app_id: 437176729644075
  secret_key: 38fabbe570f9dad2674fd5b5d8e50b42
  #app_id: 145793745551509
  #secret_key: f946593885b4af81781305206ded8185
  callback_url: "http://wydtest.dev/fb_canvas_callback" # currently not used.. one day it will be
  landing_url: "http://apps.facebook.com/wyd-testapp" # the default entry point for any non-canvas redirects
  namespace: 'wyd-testapp'
test:
  app_id: 437176729644075 # wyd-test
  secret_key: 38fabbe570f9dad2674fd5b5d8e50b42
  callback_url: "http://wydtest.dev/fb_canvas_callback"
  landing_url: "http://apps.facebook.com/wyd-testapp"
  namespace: 'wyd-testapp'
staging:
  app_id: 162564120523137
  secret_key: 0dacd2ca12e020af25767fe78f4897e6
  callback_url: ""
  landing_url: "http://apps.facebook.com/cmstg"
  namespace: 'cmstg'
production:
  app_id: 462731043755063
  secret_key: fed84440e51e21f8eb69988520dfa069
  callback_url: ""
  landing_url: "http://apps.facebook.com/critiqueme"
  namespace: 'wheresyourdollar'
