development:
  host: localhost
  database: critique_me_development

test:
  host: localhost
  database: critique_me_test

staging:
  host: staff.mongohq.com
  port: 10030
  username: seed_blocks
  password: 533dbl0ck5
  database: critique_me_stg

production:
  host: staff.mongohq.com
  port: 10030
  username: seed_blocks
  password: 533dbl0ck5
  database: critique_me_stg